#!/bin/bash -l
#
# GROMACS on Piz Daint: 1 nodes, 12 MPI tasks per node, 1 OpenMP threads per task no hyperthreading (--ntasks-per-core=1)
#
#SBATCH --job-name=min
#SBATCH --time=1:00:00
#SBATCH --nodes=3
#SBATCH --ntasks-per-node=12
#SBATCH --ntasks-per-core=1
#SBATCH --cpus-per-task=1
#SBATCH --hint=nomultithread
#SBATCH --constraint=gpu
#========================================
# load modules and run simulation
module load daint-gpu
module load GROMACS
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export CRAY_CUDA_MPS=1

echo STARTING AT $(date)
gmx grompp -f step4.0_minimization.mdp -o step4.0_minimization.tpr -c step3_charmm2gmx.pdb -r step3_charmm2gmx.pdb -p topol.top -maxwarn 1
srun gmx_mpi mdrun -v -deffnm step4.0_minimization -ntomp 1
echo FINISHED AT $(date) 
