#!/bin/bash -l
#
# GROMACS on Piz Daint: 1 nodes, 12 MPI tasks per node, 1 OpenMP threads per task no hyperthreading (--ntasks-per-core=1)
#
#SBATCH --job-name=p1
#SBATCH --time=24:00:00
#SBATCH --nodes=3
#SBATCH --ntasks-per-node=12
#SBATCH --ntasks-per-core=1
#SBATCH --cpus-per-task=1
#SBATCH --hint=nomultithread
#SBATCH --constraint=gpu
#========================================
# load modules and run simulation
module load daint-gpu
module load GROMACS
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export CRAY_CUDA_MPS=1

echo STARTING AT $(date)
gmx grompp -f step5_production.mdp -o step5_1.tpr -c step4.1_equilibration.gro -n index.ndx -p topol.top -maxwarn 1
srun gmx_mpi mdrun -deffnm step5_1 -ntomp 1 
echo FINISHED AT $(date) 
